Repository amsa-code/risky, pull requests merged in 2024-03, with the labels that each got.

#217 Add risky bom
  .gitignore
  pom.xml
  risky-bom/pom.xml
Labels: enhancement

#219 reuse shared GHA
  .github/workflows/ci.yml
  .github/workflows/deploy-release-to-maven-central.yaml
  .github/workflows/release-drafter.yml
  ais/src/main/java/au/gov/amsa/ais/AisNmeaMessage.java
  ais/src/main/java/au/gov/amsa/ais/Util.java
  ais/src/main/java/au/gov/amsa/ais/message/AisBaseStation.java
  ais/src/main/java/au/gov/amsa/util/nmea/NmeaMessageParser.java
  geo-analyzer/src/main/java/au/gov/amsa/geo/BinaryCellValuesObservable.java
  geo-analyzer/src/main/java/au/gov/amsa/util/navigation/Position.java
  streams/src/main/java/au/gov/amsa/streams/StringSockets.java
Labels: enhancement

#218 use dptMngt for slf4j and mark bindings as test scope
  ais-router/pom.xml
  ais/pom.xml
  animator/pom.xml
  behaviour-detector/pom.xml
  craft-analyzer-wms/pom.xml
  formats/pom.xml
  geotools-extras/pom.xml
  ihs-reader/pom.xml
  pom.xml
  renjin/pom.xml
  streams/pom.xml
Labels: bug

#220 Use amsa parent pom
  ais-parquet/pom.xml
  ais-router/pom.xml
  ais/pom.xml
  ais/setupMaven.sh
  animator/pom.xml
  behaviour-detector/pom.xml
  craft-analyzer-wms/pom.xml
  formats/pom.xml
  geo-analyzer/pom.xml
  geotools-extras/pom.xml
  ihs-reader/pom.xml
  pom.xml
  spark/pom.xml
  streams/pom.xml
Labels: enhancement

#228 re-add animator module
  ais-parquet/pom.xml
  ais-router/pom.xml
  ais/pom.xml
  animator/pom.xml
  animator/src/main/java/au/gov/amsa/animator/ModelManyCraft.java
  animator/src/main/java/com/github/davidmoten/util/MapWithIndex.java
  behaviour-detector/pom.xml
  craft-analyzer-wms/pom.xml
  formats/pom.xml
  geo-analyzer/pom.xml
  geotools-extras/pom.xml
  h2spatial/pom.xml
  ihs-reader/pom.xml
  pom.xml
  renjin/pom.xml
  risky-bom/pom.xml
  streams/pom.xml
Labels: maintenance
